### ISSUE TITLE
BelongsToOne生成的SQL语句会有重复的where条件

### ISSUE THREAD

**Issue by hvsy** [zingimmick/laravel-eloquent-relationships#74]
https://github.com/zingimmick/laravel-eloquent-relationships/blob/cd419b8fc37dffdf2b5019c2b4e6a7ea9b488493/src/Relations/BelongsToOne.php#L93-L102

这里会执行两次 addWhereConstraints , 一次在parent::addConstraints中, 一次在 100 行

**Comment by zingimmick** [comment]
打包了个新版本 [2.2.1](https://github.com/zingimmick/laravel-eloquent-relationships/releases/tag/2.2.1) 修复了这个问题，可以再试一下。
